int change_shields(int *shields);
int changescore(int score,int *shields);
int collision(int x1,int y1,int xsize,int ysize,int x2,int y2,int x2size,int y2size);
char *tb1_data_file(char *name,char *store);
void ReadConfigFile(int CDROMmode);
int showhiscore(int showchart);
void write_hs_list(int score,char *hiname);
void help();
void setupsidebar(int score,int hiscore,int shields);
void options();
void savegame(int level,int begin_score,int begin_shields);
void loadgame();
void story();
void credits();
void about();
void playthegame(int level,int sc,int sh);
